apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 5672
      protocol: TCP
      name: amqp
    - port: 15672
      protocol: TCP
      name: management
  selector:
    app: rabbitmq